language: ruby

before_install:
  - gem update --system
  - gem install bundler
  - gem update bundler

rvm:
  - 2.1.9
  - 2.2.6
  - 2.3.3
  - 2.4.0
  - jruby-9.0.5.0
  - jruby-head

cache: bundler
sudo: false
fast_finish: true
