language: ruby

before_install:
  - "echo 'gem: --no-document' > ~/.gemrc"
  - gem update --system
  - gem install bundler

rvm:
  - 2.4.5
  - 2.5.5
  - 2.6.2
  - jruby-9.2.6.0

cache: bundler
sudo: false
fast_finish: true
